### ISSUE TITLE
Add Fleet Tracking

### ISSUE THREAD

**Issue by Wizofgoz** [evecommander/evecommander-api#39]
- [x] Add models/migrations for FleetMembers, FleetWings, FleetSquads, and pivot tables

- [ ] Create cron task to query ESI for updates to active fleets. Fleets are active if they have an ID and are not pending, cancelled, or completed

- [x] When updating models, changes must be kept to provide a graphical history for them
